stop-words = "lemur-stopwords.txt"
prefix = "/data"
dataset = "trec-robust"
corpus = "gz.toml"
index = "trec-index"
query-judgements = "/data/trec-robust/trec-qrel"

[query-runner]
query-path = "/data/trec-robust/trec-queries"
query-id-start = 1

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
